---
- name: Set up cron
  sudo: yes
  cron:
    name="CloudWatch"
    minute=*/{{cron_interval}}
    job="{{script_dir}}mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
    state=present