---
- name: Set up cron
  sudo: yes
  cron:
    name="CloudWatch"
    minute=*/5
    job="/var/local/cloudwatch/mon-put-instance-data.pl --mem-util --disk-space-util --disk-path=/ --from-cron"
    state=present