---
- name: Create CPU utilization metric alarm
  local_action: ec2_metric_alarm
    state=present
    name="{{ec2_facts.ansible_facts.ansible_ec2_instance_id}}""-disk-low"
    metric="DiskSpaceAvailable"
    namespace="AWS/EC2"
    statistic=Average
    comparison="<="
    threshold=25.0
    unit="Percent"
    period=300
    evaluation_periods=1
    description="It will be triggered when available disk space is less than 25%"
    dimensions={"InstanceId":"{{ec2_facts.ansible_facts.ansible_ec2_instance_id}}"}
    alarm_actions=["arn:aws:sns:us-east-1:406822941806:infrastructure_alarms"]
    ok_actions=]"arn:aws:sns:us-east-1:406822941806:infrastructure_alarms"]
